apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  labels:
    app: hello-app
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
  - protocol: TCP
    port: 80         # Exposed port
    targetPort: 80   # Target container port
    nodePort: 30007  # Optional, Kubernetes will allocate if not specified