apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-2
  labels:
    app: hello-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app-2
  template:
    metadata:
      labels:
        app: hello-app-2
    spec:
      containers:
      - name: hello-app-2
        image: nginxdemos/hello:latest  # Prebuilt image to show a Hello page
        ports:
        - containerPort: 80