apiVersion: v1
kind: Service
metadata:
  name: hello-app-2-service
  labels:
    app: hello-app-2
spec:
  type: NodePort
  selector:
    app: hello-app-2
  ports:
  - protocol: TCP
    port: 80         # Exposed port
    targetPort: 80   # Target container port
    nodePort: 30008  # Optional, Kubernetes will allocate if not specified